<?php
$servername = "localhost";
$username = "admin";
$password = "admin";
$dbname = "SNBDB";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

// sql to create table
$sql = "CREATE TABLE SNBFormTable (
id  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
registerType  VARCHAR(50) NOT NULL,
passportNum   VARCHAR(30) NOT NULL,
salutation  VARCHAR(20) NOT NULL,
fullName  VARCHAR(50) NOT NULL,
surname   VARCHAR(30) NOT NULL,
gender  VARCHAR(10),
race  VARCHAR(10),
specifyRace   VARCHAR(30),
birthDate   DATE,
nationality   VARCHAR(20),
birthPlace  VARCHAR(20),
marital   VARCHAR(20),
religion  VARCHAR(20),
specifyReligion   VARCHAR(30),
citizenshipYear   INT(4),
specifyNationality  VARCHAR(30),
residency   VARCHAR(30),
specifyResidency  VARCHAR(60),
email   VARCHAR(60),
email2  VARCHAR(60),
homeTelephone   VARCHAR(20),
officeTelephone   VARCHAR(20),
mobileTelephone   VARCHAR(20),
homeAddress   VARCHAR(150),
qualCountry   VARCHAR(20),
qualUniversity  VARCHAR(60),
qualType  VARCHAR(20),
specifyQualType   VARCHAR(60),
qualName  VARCHAR(60),
qualAbbreviate  VARCHAR(10),
qualSpecialty   VARCHAR(60),
qualProgType  VARCHAR(10),
qualDuration  INT(3),
qualStartDate   DATE,
qualEndDate   DATE,
qualYearObtained  INT(4),
qualTwinning  VARCHAR(5),
specifyTwinning   VARCHAR(60),
table1Country1  VARCHAR(20),
table1Country2  VARCHAR(20),
table1Country3  VARCHAR(20),
table1Country4  VARCHAR(20),
table1Country5  VARCHAR(20),
table1University1   VARCHAR(60),
table1University2   VARCHAR(60),
table1University3   VARCHAR(60),
table1University4   VARCHAR(60),
table1University5   VARCHAR(60),
table1StartDate1  DATE,
table1StartDate2  DATE,
table1StartDate3  DATE,
table1StartDate4  DATE,
table1StartDate5  DATE,
table1EndDate1  DATE,
table1EndDate2  DATE,
table1EndDate3  DATE,
table1EndDate4  DATE,
table1EndDate5  DATE,
table2StartDate1  DATE,
table2StartDate2  DATE,
table2StartDate3  DATE,
table2EndDate1  DATE,
table2EndDate2  DATE,
table2EndDate3  DATE,
table2Details1  TEXT,
table2Details2  TEXT,
table2Details3  TEXT,
licenseExam   VARCHAR(5),
licenseExamDetails  TEXT,
passExam  VARCHAR(5),
notPassExamDetails  TEXT,
table3Country1  VARCHAR(20),
table3Country2  VARCHAR(20),
table3Country3  VARCHAR(20),
table3University1   VARCHAR(60),
table3University2   VARCHAR(60),
table3University3   VARCHAR(60),
table3QualName1   VARCHAR(60),
table3QualName2   VARCHAR(60),
table3QualName3   VARCHAR(60),
table3QualAbbreviate1   VARCHAR(10),
table3QualAbbreviate2   VARCHAR(10),
table3QualAbbreviate3   VARCHAR(10),
table3ProgType1   VARCHAR(10),
table3ProgType2   VARCHAR(10),
table3ProgType3   VARCHAR(10),
table3Specialty1  VARCHAR(60),
table3Specialty2  VARCHAR(60),
table3Specialty3  VARCHAR(60),
table3YearConfer1   INT(4),
table3YearConfer2   INT(4),
table3YearConfer3   INT(4),
table4Country1  VARCHAR(20),
table4Country2  VARCHAR(20),
table4Country3  VARCHAR(20),
table4University1   VARCHAR(60),
table4University2   VARCHAR(60),
table4University3   VARCHAR(60),
table4Department1   VARCHAR(60),
table4Department2   VARCHAR(60),
table4Department3   VARCHAR(60),
table4Discipline1   VARCHAR(60),
table4Discipline2   VARCHAR(60),
table4Discipline3   VARCHAR(60),
table4StartDate1  DATE,
table4StartDate2  DATE,
table4StartDate3  DATE,
table4EndDate1  DATE,
table4EndDate2  DATE,
table4EndDate3  DATE,
table4TotalHours1   INT(4),
table4TotalHours2   INT(4),
table4TotalHours3   INT(4),
table5DateJoin1   DATE,
table5DateJoin2   DATE,
table5DateJoin3   DATE,
table5DateLeft1   DATE,
table5DateLeft2   DATE,
table5DateLeft3   DATE,
table5Country1  VARCHAR(20),
table5Country2  VARCHAR(20),
table5Country3  VARCHAR(20),
table5Organisation1   VARCHAR(60),
table5Organisation2   VARCHAR(60),
table5Organisation3   VARCHAR(60),
table5Department1   VARCHAR(60),
table5Department2   VARCHAR(60),
table5Department3   VARCHAR(60),
table5Designation1  VARCHAR(60),
table5Designation2  VARCHAR(60),
table5Designation3  VARCHAR(60),
table5Type1 VARCHAR(10),
table5Type2 VARCHAR(10),
table5Type3 VARCHAR(10),
table5PTHours1  INT(3),
table5PTHours2  INT(3),
table5PTHours3  INT(3),
table6StartDate1  DATE,
table6StartDate2  DATE,
table6StartDate3  DATE,
table6EndDate1  DATE,
table6EndDate2  DATE,
table6EndDate3  DATE,
table6Details1  TEXT,
table6Details2  TEXT,
table6Details3  TEXT,
table7Country1  VARCHAR(20),
table7Country2  VARCHAR(20),
table7Country3  VARCHAR(20),
table7Authority1  VARCHAR(60),
table7Authority2  VARCHAR(60),
table7Authority3  VARCHAR(60),
table7Category1 VARCHAR(60),
table7Category2 VARCHAR(60),
table7Category3 VARCHAR(60),
table7LicenceNum1 VARCHAR(60),
table7LicenceNum2 VARCHAR(60),
table7LicenceNum3 VARCHAR(60),
table7RegisterDate1 DATE,
table7RegisterDate2 DATE,
table7RegisterDate3 DATE,
table7CurrentPCNum1 VARCHAR(60),
table7CurrentPCNum2 VARCHAR(60),
table7CurrentPCNum3 VARCHAR(60),
table7PCStartDate1  DATE,
table7PCStartDate2  DATE,
table7PCStartDate3  DATE,
table7PCEndDate1  DATE,
table7PCEndDate2  DATE,
table7PCEndDate3  DATE,
activityStatus  VARCHAR(20),
notWorkingReason  TEXT,
PTHours INT(3),
currentAppt VARCHAR(60),
currentOrganisation VARCHAR(60),
currentNatureOfWork VARCHAR(20),
currentWorkSpecify  VARCHAR(60),
currentDepartment VARCHAR(60),
currentDateJoin DATE,
currentDateLeft DATE,
declaration1  VARCHAR(5),
declaration1Details TEXT,
declaration2  VARCHAR(5),
declaration2Details TEXT,
declaration3  VARCHAR(5),
declaration3Details TEXT,
declaration4Row1  VARCHAR(20),
declaration4Row2  VARCHAR(20),
declaration4Row3  VARCHAR(20),
declaration5  VARCHAR(60)
)";

if ($conn->query($sql) === TRUE) {
    echo "Table SNBFormTable created successfully";
} else {
    echo "Error creating table: " . $conn->error;
}

$conn->close();
?>
